### PR TITLE
Custom headers

### PR DESCRIPTION
**Pull request by Ilaiwi**
**Issue Number**

#349 

**Overview of PR**

this PR adds the following features:

1. render more headers in the header section 
2. add the ability to add completely customized headers.

To checkout, the work run the demo and chose `customHeaders` demo

customheaders

 _**This work is still really really early and only to show core concept of the feature and to show progress**_

### TODO

- [x] fix drag items bug where extra custom headers cause items to not be correctly positioned correctly dragging
- [x] convert to propGetter pattern
- [x] add style and classnames props to customize headers root element

- [x] add props to style root element and add classnames to root element

- [x] add render prop for `DateHeader` for intervals
- [x] fix broken tests

- [x] add documentation

- [x] add tests for custom headers

- [x] delete format props
- [x] refactor and test 
- [x] decide what to do with sticky header prop
- [x] handle `headerRef` prop

- [x] maybe unify `CustomHeader` and `VerticalLines` label width calculation

- [x] make sure plugins don't break

- [x] delete sidebarContent and rightSidebarContent readme

- [x] delete `headerLabelGroupHeight` and `headerLabelHeight`
- [x] delete header css classes
- [x] custom header/day header pass primary/secondary via unit
- [x] pass components and functions for render prop
- [x] remove format object option from labelFormat
- [x] default styles in DateHeader => move to classnames and don't provide them if provide interval renderer
- [x] fix custom header docs (interval)
- [x] must pass height to custom headers? how do we fix this?
- [x] check if programmatically scrolling example work
- [x] write breaking change docs
- [x] cleanup old code
- [ ] handle touch state in `TimelineElementsHeader`

- [ ] fix a bug, where headers interval borders are not aligned with the vertical lines, form the calendar

- [ ] add an option to deal with `unit` as an interval of time
- [ ] pass `unit` as interval iterateTimes

### CODE REVIEW

**Comment by digitaldesigndj** [comment]
I really need exactly this feature 👍 Is there anything I can do to help it along?

**Comment by Ilaiwi** [comment]
@digitaldesigndj nice work! I checked out your work and noticed that you where calculating `labelWidth` to `interval` but it is already in the object. 
I am currently writing the documentation and I would always appreciate feedback about the API and code reviews :)
Also if you want to tackle any of the TODOs feel free to do so and open a PR in it

**Comment by Ben-All** [comment]
Wondering if this will be incorporated

**Comment by Ilaiwi** [comment]
@Ben-All I am working on it. Cant say when though

**Comment by dimagimburg** [comment]
Hi @Ilaiwi , first of all thank you very much for your contribution, I find react-calendar-timeline very useful and modular! When custom headers will be released, will I be able to set fixed width to header label? I mean I don't want the timeline cells to be responsive, I want them to be fixed width no matter what is the width of the screen. Is this something related to current feature? is it already supported?

Thanks again.

**Comment by Ilaiwi** [comment]
@dimagimburg, could you please open an issue with your request? I will track it and answer it there because I am not sure

**Pull request merged**
