### PR TITLE
Issue 182 - Fix issue with drag not ending if you mouse leave scroll component

### PR DESCRIPTION
**Pull request by mcMickJuice**
Fixes https://github.com/namespace-ee/react-calendar-timeline/issues/182

### CODE REVIEW

**Comment by PimentelKJ** [comment]
Thank goodness, this was a frustrate. Many thank.

**Comment by timojokinen** [comment]
@mariusandra can this PR be merged? Would really appreciate this bugfix.

**Comment by mariusandra** [comment]
Hey guys, I'm really not involved with this project right now. But if any of you would like to become maintainers and get this merged, please let @madisvain know

**Comment by yanickrochon** [comment]
If this was resolved, this PR should be closed and the related issue referenced to the actual PR. Just saying.

**Pull request merged**
