### PR TITLE
Fix for Issue 173 - Changed location of time delta check

### PR DESCRIPTION
**Pull request by Biohazord**
This is a proposed fix for the [issue](https://github.com/namespace-ee/react-calendar-timeline/issues/173) I opened up. I've ran the tests and linting. Everything passes. I'm still new to contributing to github projects so please let me know if I did anything wrong.

### CODE REVIEW

**Comment by mcMickJuice** [comment]
https://github.com/namespace-ee/react-calendar-timeline/issues/173

**Comment by mcMickJuice** [comment]
Hi @Biohazord this all looks good. Just one question: is there a visual bug or obvious bug without this fix?  I'm new to maintaining the project so just wanna know what problem this fixes from the users perspective.

**Comment by Biohazord** [comment]
It's been a while since I've looked at this so I forget exactly what happens. The one thing I do know off hand is that that the date "toast" that appears in the bottom left will remain. I believe there was something else I observed. I'll have to dive back into it tomorrow and update here.

**Comment by mcMickJuice** [comment]
That'd be great. Thank you!

**Comment by mcMickJuice** [comment]
That'd be great. Thank you!

**Comment by mcMickJuice** [comment]
That'd be great. Thank you!

**Pull request merged**
