### PR TITLE
Add onItemDrag prop to <Timeline />

### LINKED ISSUE #517: Ability to customize the InfoLabel
**Is your feature request related to a problem? Please describe.**
It could be nice if we show customized information while dragging (moving or resizing) items (currently only showing time and groupLabelKey).

**Describe the solution you'd like**
Provide a renderer for InfoLabel the same way like groupRenderer or itemRenderer.

**Describe alternatives you've considered**
At least give an option to hide InfoLabel while dragging. (Sometimes you do not like it to show)

**Additional context**
I checked your feedback of the request to customize the header (#48)
But I think this one is much easier and really does not take so much resource, so I will be very graceful this time if you do not close this one that recklessly.

### PR DESCRIPTION
**Pull request by bettymakes**
**Issue Number**
#517 

**Overview of PR**
⚠️ I had initially shipped a renderer for the `infoLabel` in [PR #606](#606). However, I lean towards this implementation to resolve #517 so I've gone ahead and closed #606.

### 🤔 Considerations
I initially submitted [PR #606](#606) a few days ago. That PR introduced a `renderer` prop to enable `InfoLabel` customizations on `drag` or `move` of an Item. My main impetus towards the initial approach of providing a `renderer` as opposed to an `event handler` to resolve #517 was because I felt reticent to introduce a breaking change, [removing the `<InfoLabel />` altogether](https://github.com/namespace-ee/react-calendar-timeline/pull/606) as advised by @Ilaiwi in the Issue Thread.

That said, my team has encountered another use-case where we need access to the `moving`/`resizing` event of an Item. So I've come back for round two and have double back on resolving the story as per @Ilaiwi's initial suggestion.

### ⚒ What's changed
- Added a `onDragItem` prop to `<Timeline />`
  - `onDragItem` is called during `moving` or `resizing` of an Item 
  - `onDragItem` provides an object with the following values:
    - 1️⃣ `eventType`: a String value of either `move` or `resize`
    - 2️⃣ `itemId`: a Number value of the Item being moved or resized
    - 3️⃣ `time`: the UNIX time in milliseconds
    - 4️⃣ `edge`: on `resize`, a String value of either `left` or `right`
    - 5️⃣ `newGroupOrder`: on `move`, the index position of the new group the item has moved to
- As per @Ilaiwi's [note](https://github.com/namespace-ee/react-calendar-timeline/issues/517#issuecomment-470069004), the `<InfoLabel />` has been removed altogether
  - The `<InfoLabel />` component has been moved to the `demo-custom-info-label` directory so people can still search for it within the codebase

### 🧪 Testing
Similar to my note in #606, I'm still unsure about how to test this. Happy to hear your suggestions 👍.

### 👀 Demo Example
A demo example has been included. This example renders a `<CustomInfoLabel />` on `move` or `resize` of an Item.
Resizing and Moving an Item on the Timeline, displays a Custom Info Label

### 📝 To Dos
I still need to update the Changelog. I just wanted to get this PR up so we can have a discussion around this @Ilaiwi.

_Don't forget to update the CHANGELOG.md file with any changes that are in this PR_

### CODE REVIEW

**Comment by Ilaiwi** [comment]
@bettymakes thank you for the pull request. Yes, this makes much more since than the previous approach. This is more of inversion of control approach which always prefers

for testing, I am okay with not having tests for this one since we don't have a lot of inclusive tests that would test the whole component flow

**Comment by bettymakes** [comment]
Thanks for the feedback @Ilaiwi 😊🙌.

I've updated the `README` and the `CHANGELOG`. We should be good to go. Let me know if there's anything else I need to revise.

Thanks a bunch!

**Comment by Ilaiwi** [comment]
@bettymakes This might take a bit more type to merge because I am thinking a better way to inform everyone that the InfoLabel feature will be deleted and replaced by your solution

**Comment by bettymakes** [comment]
I had initially kept the `<InfoLabel />` component around in the `Demo` directory, just in case folks want a resource to refer back to. I can definitely remove it though 😊 👍. 

I've updated the PR with the `<InfoLabel />` removed.

If there's any way I can support you with a roll out plan/communicating the deprecation of `<InfoLabel />`, let me know. Happy to help!

**Pull request merged**
