### PR TITLE
Fix issues related to position of MarkerCanvas

### PR DESCRIPTION
**Pull request by mcMickJuice**
**Issue Number**

#378 
#383 

**Overview of PR**

Move `MarkerCanvas` up to wrap all timeline elements in canvas (items, groups, etc)

### CODE REVIEW

**Comment by mcMickJuice** [comment]
@Ilaiwi would you mind reviewing and smoke testing this change?  It looks to fix both issues, just want another pair of eyes.  Thanks!

**Comment by Ilaiwi** [comment]
I get this error in console:

`Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `MarkerCanvas`, expected a single ReactElement.` 

branch `fix/marker-canvas` I added no changes

**Comment by Ilaiwi** [comment]
The problem was from my code and now this works fine and solved all my problems. 
I still think though we should add an issue to discuss propagating events between calendar layers
I think markers still be considered a layer with `items`, `vertical lines`, `horizontal lines` and `plugins` but for now this is very good solution

**Comment by mcMickJuice** [comment]
>Warning: Failed prop type: Invalid propchildrenof typearraysupplied toMarkerCanvas, expected a single ReactElement.

Fixed with https://github.com/namespace-ee/react-calendar-timeline/pull/388/commits/529001ab4a575d3eb240d72b3208d8802a4f0f85

**Pull request merged**
