### PR TITLE
[Core] Updated dependencies. Fixed warning in Header.jsx

### PR DESCRIPTION
**Pull request by xmityaz**
Updated dependencies, including react 15.0.*
At least it works correctly for me. Probably would be better to test deeper, as I could miss something ('npm run lint' in terminal doesn't work for me either with new and with old dependencies)

Fixed warning in Header.jsx:

### CODE REVIEW

**Comment by ochervak** [comment]
Cool! Many thanks for your PR

**Comment by lnagel** [comment]
This package should remain usable both in projects with react 0.14.* or react 15.0.*.

**Comment by ochervak** [comment]
what about accepting ? ;)

**Comment by madisvain** [comment]
We'll review this shortly. Sorry the delay.

**Comment by mariusandra** [comment]
Hey, I checked and everything seems to work. 0.7.6 pushed out.

**Pull request merged**
