### PR TITLE
Updating custom marker's date if date changes

### PR DESCRIPTION
**Pull request by kevinmanncito**
**Issue Number**
[421](https://github.com/namespace-ee/react-calendar-timeline/issues/421)

**Overview of PR**
When the date prop on the public `CustomMarker` changes the `markers` array in the `TimelineMarkersProvider` state also needs to change. The fix here is just calling the unsubscribe from the public `CustomMarker` when the date changes and then calling the `subscribeMarker` func again.  The change in date is detected by using the `componentDidUpdate` lifecycle method.

### CODE REVIEW

**Comment by Ilaiwi** [comment]
Thank you for this and thanks for your first contribution. I think this shouldn't be the way to solve it. I think there could be a better way to solve this by passing the new date. I am thinking about creating another method which will be something like `updateProps` or something that will pass the new props to the `CustomMarler` implementation. what do you think?
As for your idea, I think this way is okay but I don't see any extra benefits than changing the key which will basically resubscribe a marker.

**Comment by kevinmanncito** [comment]
That was actually my initial thought but I couldn't see a way of getting to the `_id` attribute from the public `CustomMarker` to pass into the `TimelineMarkersProvider ` in order to know which marker to update. Maybe I can use something else to know which marker to update or maybe I was missing something. I can double check again tonight and see if there is a clean way of using an `updateProps` method and possibly update this PR if you'd like.

**Comment by Ilaiwi** [comment]
what about getting another method in the return value from `subscribe` beside `unsubscribe` something like `updateProps`? it would be something like [`rerender`](https://github.com/kentcdodds/react-testing-library#rerender)

**Comment by Ilaiwi** [comment]
and I would really appreciate any help I could get 👍

**Comment by kevinmanncito** [comment]
Okay cool, I'll take a look later today at doing that

**Comment by kevinmanncito** [comment]
@Ilaiwi  updated PR. Let me know if that is what you were thinking.

**Comment by kevinmanncito** [comment]
Sure, I will get to that this week and update the PR

**Comment by kevinmanncito** [comment]
@Ilaiwi  Sounds good, thanks for this library, we are putting it to good use on a project right now. I'll definitely let you know if I run into any more issues or find anything else I could contribute.

**Comment by Ilaiwi** [comment]
Please feel free to do so. You can find issues to contribut to using the help wanted label

**Pull request merged**
