### PR TITLE
Drag n drop unto timeline

### PR DESCRIPTION
**Pull request by prh7**
**Issue Number**

Link to issue this PR addresses.  If no issue exists, please provide reasoning for PR.

**Overview of PR**

Provide an overview of the changes in this PR.

_Don't forget to update the CHANGELOG.md file with any changes that are in this PR_

### CODE REVIEW

**Comment by Ilaiwi** [comment]
this is great! I've been working on implementing a row renderer that might help support this as well. I am gonna compare them when I have a good version of my solution
@prh7 thank you so much for the work

**Comment by prh7** [comment]
@Ilaiwi - Can you provide code sandbox of how you are intending to drag and drop of item from one timeline to the other?

**Comment by Ilaiwi** [comment]
@prh7 I am working on it. It is gonna take few weeks I guess to get their. I might just post the branch I am doing the work in here.

could you also please resolve the conflict and make the PR aginst develop instead of master?

**Comment by prh7** [comment]
@Ilaiwi - Can I get access as a contributor to the repository? Somehow, I ain't a part of contributor list. I fixed the merge conflicts and made a small demo 'dragDropTimeline' along with other demos locally.

**Comment by Ilaiwi** [comment]
@prh7 you don't need to be to fix the conflict. You can set up this repo as the upstream source
`git remote add upstream https://github.com/namespace-ee/react-calendar-timeline.git`
 and do 
`npm pull upstream develop`

**Comment by Ilaiwi** [comment]
@prh7 t[his is only a prototype for now](https://github.com/namespace-ee/react-calendar-timeline/blob/rowRenderer/demo/app/demo-main/index.js). But this is what to come. 
This uses a row renderer feature that I am prototyping in. The drag and drop here is implemented via react-dnd. The cool thing about this feature that the dnd is not built into the timeline but added on top of it.

**Comment by prh7** [comment]
@Ilaiwi - Thank you very much for the great work done. I have two questions:
1. Can we easily integrate different layers like Gantt layers, etc,. on top of the timeline ?
2. How performant is it going to behave if we integrate different layers in your perspective?

**Comment by Ilaiwi** [comment]
@prh7 
1- I am going to experiment with gantt with this new API in the next few months but not sure it will make the public API unfortunately
2- performance-wise this new row renderer concept should have huge positive impact on the performance. for the layers, it will depend on your implementation more than how the library handles things (please note code I linked is a prototype and the idea here is not performance)

**Comment by Ilaiwi** [comment]
I released `rowRenderer` in beta which has an example that does this
https://github.com/namespace-ee/react-calendar-timeline/issues/656#issuecomment-548023771

**Pull request closed without merging**
