### PR TITLE
Feature/multiselect with fix

### PR DESCRIPTION
**Pull request by aodinok**
This PR is small fix in this: https://github.com/namespace-ee/react-calendar-timeline/pull/131
I was trying to push this fix directly to above PR but, looks like I don't have required rights, so I've created another one. 

This PR fixes issue with  app crash mentioned in this comment: https://github.com/namespace-ee/react-calendar-timeline/pull/131#issuecomment-319683525

### CODE REVIEW

**Comment by aodinok** [comment]
@mariusandra Can you please take a look one more time on this feature, it's mostly work done by @signalwerk, with small fix from me: https://github.com/namespace-ee/react-calendar-timeline/pull/198/commits/f4ea1077c6f621d69dc3b058fd3536fc67f59059

**Comment by andy-dorman** [comment]
Any idea what the current status of this work is? I’d really like to see this added if it’s ready

**Comment by vasdee** [comment]
@mcMickJuice @andy-dorman see https://github.com/namespace-ee/react-calendar-timeline/pull/314 for a new pull-request that is this pull, refactored with the 0.16 branch.

**Comment by mcMickJuice** [comment]
Closing in favor of https://github.com/namespace-ee/react-calendar-timeline/pull/314

**Pull request closed without merging**
