### PR TITLE
Updated all dependencies

### PR DESCRIPTION
**Pull request by Remco4EF**
**Issue Number**

Link to issue this PR addresses.  If no issue exists, please provide reasoning for PR.

**Overview of PR**

I've updated all dependencies to latest versions available. So React 18, ditched create-react-context nom package and so on.

Only thing remaining  is testing support: enzyme is not up to date anymore.....

Use as you please.
_Don't forget to update the CHANGELOG.md file with any changes that are in this PR_

### CODE REVIEW

**Comment by samuk190** [comment]
lets fork this project and merge all ?

**Comment by Ilaiwi** [comment]
@Remco4EF @remcoblumink @samuk190 If you would review and test this PR. I would be happy to merge and release these changes.

**Comment by Remco4EF** [comment]
**Big notice!**

We completely moved it to using typescript and using vite as bundler. 
As a consequence, most tests are broken atm. If someone can give us a pointer on how to get the tests up and running that would be awesome. Since Enzyme is 5 years old and not react 18 supported.

(though we just use this code in production for our use case)

**Comment by Ilaiwi** [comment]
I am planing to release this soon but if more people are willing to test the new changes on their apps that would be appriciated.

**Comment by kodobrody** [comment]
@Ilaiwi hey there, I'm doing a rewrite of my app with use of next.js 15 and react 19, however due to old context library I'm not able to use this library. Would you be able to share a new version as a beta possibly?

**Comment by Ilaiwi** [comment]
released as 0.30.0-beta.1
I will release this to latest as soon as more people test the new updates

**Comment by kodobrody** [comment]
I'll test as soon as I can. God's work!

**Comment by kodobrody** [comment]
@Ilaiwi I have following error while trying to render the basic example:
`TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')`, maybe it's due to react version being `>= 18` and I have 19 in my project?

**Pull request merged**
